### ISSUE TITLE
In case of long url data is not getting captured

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#11]
Please refer to files `chrome_2_perf_smava.py` and `config_smava.yaml`

When the url value is really long, it doesn't capture performance data

**Expected**

```
FUNCTIONAL: Page sucks!
('PERFORMANCE was', 'GOOD! - ', '1322', '/ 2000')
```

**Actual** 
`
FUNCTIONAL: Page sucks!`

https://gist.github.com/vikramvi/b16410d64e20d061d8672ff1bd82f52a

https://gist.github.com/vikramvi/58bc4b24b102546f42e7bd8955d37e81

Strangely I've one more test case with longer url value and it works fine

Refer to `chrome_2_perf_check24.py`

https://gist.github.com/vikramvi/8fb60a03ecc549d7b3b5329105b458bd

Please clarify what am I doing wrong here

**Comment by Verkurkie** [comment]
For the test that doesn't work, can you capture the contents of the TIMINGS variable and post it? I'd like to see if the full URL is in the `url` key ... meanwhile, i will do some testing with your .py script to reproduce this ...

**Comment by vikramvi** [comment]
Please find value of `TIMINGS` variable

https://gist.github.com/vikramvi/ef29d22519428616d5a5adcf20bfeb0c

url which is causing this is

`https://suchen.mobile.de/fahrzeuge/financingLandingpage.html?id=248239597&ab.smava=test&damageUnrepaired=NO_DAMAGE_UNREPAIRED&isSearchRequest=true&pageNumber=1&scopeId=C&action=topOfPage&top=1:3&entrypoint=vip_left_column_TestNeu&dartPrice=8980&dartDuration=84`

**Comment by vikramvi** [comment]
Issue has been verified fixed. Thanks a ton for help @Verkurkie
