### ISSUE TITLE
Running the script from inside the elasticsearch container is failing

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#12]
With latest changes, I'm getting below error

```
docker exec -it df9f2ae3bf5c python ./import/import.py
>>> You did not provide any or all of the arguments - defaults will be used!
Traceback (most recent call last):
  File "./import/import.py", line 75, in <module>
    schema = 'https://' if OPTIONS.usessl is not False else 'http://'
AttributeError: 'Namespace' object has no attribute 'usessl'
```
Please review

I think https://github.com/Verkurkie/timings-docker/commit/07b54d9ff060e76c65e50a10e867b295e8acaa62#diff-1ed3d93fb847759bfc2b64b7a7d0a47c has caused this error

Please note I'm not passing any arguments in this command

**Comment by vikramvi** [comment]
@Verkurkie can you please look into this issue, it's blocking from execution of test script. Thanks in advance.

**Comment by Verkurkie** [comment]
Just pushed https://github.com/Verkurkie/timings-docker/commit/b1e62771a46ea5ffbe593fe2bba726bca340555c which should fix it. Just do a `git pull` to get the updated import.py script - no more reference to `usessl`. Let me know if that worked for you & sorry for the delay

**Comment by vikramvi** [comment]
Thanks a ton for help.

Please clarify if after getting latest commit, 
- do I need to stop and delete **existing elastic container image** and download again ?

- I'm confused when to delete existing image and download new one with command ` docker-compose up --build`

**Comment by vikramvi** [comment]
I got the answer :)

Once user fetches new code change, s/he needs to stop container, delete container and delete respective image.

https://stackoverflow.com/questions/21398087/how-can-i-delete-dockers-images

Did you think of FAQ page to capture my issues and other person's ( java client ) issues as well ?

**Comment by vikramvi** [comment]
Thanks for detailed clarification, this should be part of **FAQ page**

**Comment by vikramvi** [comment]
added to https://github.com/Verkurkie/timings-docker/wiki/FAQ-page
