### ISSUE TITLE
FAQ Issue

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#13]
Till we figure out, how to collaborate on timings repo wiki page, can we consolidate all the Q&A here with tag names FAQ ?

I'm sure new users of this project will have similar queries and it will help them as well.

**Comment by vikramvi** [comment]
Q.1 page load timing should be full page load or 1st element in waterfall ?
- I've shown some data to developers
- Per them I should take timing of first element in waterfall
- Per me correct data is full page load

Please clarify what practice do you follow in godaddy ?

**Comment by vikramvi** [comment]
Q.2 [Kibana dashboard] [TIMINGS] List of URLs and PLT 
- what does mean by PLT in "75th percentile of Actual PLT" ?
- which is Baseline value in "75th percentile of Baseline"  ?

**Comment by vikramvi** [comment]
Q.3 which are the most important graphs to show to management
- When I'm looking at my own project ( e.g. godaddy.com )
- When I'm comparing with my competitor  ( e.g. https://smallbusiness.yahoo.com/ )

**Comment by kaygee** [comment]
In your experience how are teams instrumenting pages? In other words… at what point is the JS injected and the result obtained?

**Comment by kaygee** [comment]
How is the "baseline" and fields inside of it used? For example... what does the following mean in terms of building the baseline?

```
"baseline" : {
  "incl": {
    "browser": "_log_",
    "env_target": "_log_"
  }
}
```

**Comment by kaygee** [comment]
How do "{sla: pageLoadTime: <value>}}" and the baseline interact?

**Comment by kaygee** [comment]
What's the best way to troubleshoot and/or "sanity check" your data?

**Comment by Verkurkie** [comment]
I have created an FAQ page in the wiki: [wiki FAQ](https://github.com/Verkurkie/timings-docker/wiki/FAQ-page). You should be able to edit this page and/or add new pages if necessary. I think we'll keep the wiki for FAQ, tips, tricks, etc. and use the Issues section for bugs, troubleshooting, etc.

**Comment by Verkurkie** [comment]
Closing this issue now that the FAQ page has found its home in the wiki section - https://github.com/Verkurkie/timings-docker/wiki/FAQ-page
