### ISSUE TITLE
waterfall data is not consistent

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#15]
![chrome-waterfall](https://user-images.githubusercontent.com/308490/33170497-b8aae622-d048-11e7-8bc4-5a4fabf1610d.png)
![timings-waterfall](https://user-images.githubusercontent.com/308490/33170498-b8eb7e12-d048-11e7-9961-187b24358722.png)

1. Please refer to waterfall graphs from chrome browser and timings library
2. Both graphs' data don't match with each other, please clarify

**Comment by Verkurkie** [comment]
Hard to say! Is Chrome used in both cases? Same version of Chrome? The [resource API](https://www.w3.org/TR/resource-timing/) that we get our data from is supposed to match the exact loading order of _that_ browser and _that_ point in time. Usually the waterfall is pretty similar but loading order can change based on how the browser sets priorities.

**Comment by vikramvi** [comment]
Yup, I used same version of chrome browser on Ubuntu laptop with same network quality.

Can you please check for this issue on your end as well, by launching simple test case locally ?

**Comment by Verkurkie** [comment]
Just ran a test against one of our popular landing pages - i compared the first 15 resources and eyeballed the rest and, aside from a few small differences in the loading order, things are pretty much the same - as I would expect. See screenshot:

![image](https://user-images.githubusercontent.com/947053/33495297-124b3ab6-d683-11e7-80ad-66bd1389ee56.png)

**Comment by vikramvi** [comment]
Please refer to 1st entry in waterfall which is **wordpress-hosting**

- On right side time is shown as `423 ms`
- On left side in chrome time is `866 ms` for the same resource.

I'm confused why it's showing these 2 different timings ?

**Comment by Verkurkie** [comment]
Although I would agree that the two tests should be closer to each other but there are a lot of factors that can impact the performance of resources: delay in the server/backend, delay in the network (i was connected through VPN), the CPU of the test machine, instability of test environment, etc. When you're analyzing, you should always run tests multiple times - automated and even manually in Chrome. In Chrome for example, I always make sure that (a) I'm using an incognito tab and (b) caching is turned off. Then I refresh the page multiple times and watch the resource I'm interested in (using the filter features in devTools if needed) ... the results can vary from one test to the next. Golden rule for the **timings API**: run your tests often and use Kibana to review the stability of the results + compare against baseline - should get us close enough to prevent crazy changes :)

**Comment by vikramvi** [comment]
Thanks for detailed clarification, I will close this and put in FAQ as well :)

**Comment by vikramvi** [comment]
added to https://github.com/Verkurkie/timings-docker/wiki/FAQ-page
