### ISSUE TITLE
https://github.com/godaddy/timings/blob/master/CONFIG.MD [ doc issue ]

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#17]
- User has installed setup using **timings-docker**
-  In this case user can find `.config.js `file under  `timings-docker/timings/config`

please add this info to documentation, as many users will use dockerised technique to install timings api and not npm

**Comment by Verkurkie** [comment]
Good idea! I will add a table with the installation options and the corresponding location of the config file. Thanks!

**Comment by Verkurkie** [comment]
I made changes to the README of the timings repo. See: https://github.com/godaddy/timings#installing-and-running-the-api. The CONFIG doc is really meant to explain the different settings in the config file itself and i felt this belongs in the main README - comments?

**Comment by vikramvi** [comment]
thanks again :) verified fixed
