### ISSUE TITLE
ImportError: No module named timingsclient [ Jenkins only ]

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#18]
- I'm trying to do local jenkins setup to run script every hours per instructions from 

https://github.com/softwaresaved/build_and_test_examples/blob/master/jenkins/Shell.md

- `shell file` which I'm planning to run with `jenkins job` is https://github.com/vikramvi/timings-demo/blob/master/py/job.sh

- jenkins job error

code : https://github.com/vikramvi/timings-demo/tree/master/py

```
Building in workspace /home/vingleshwar/Documents/VikramIngleshwar/PerformanceTesting/timings-demo/py
[py] $ /bin/sh -xe /tmp/jenkins1829599534415325144.sh
+ pip install selenium
Collecting selenium
  Downloading selenium-3.8.0-py2.py3-none-any.whl (941kB)
Installing collected packages: selenium
Successfully installed selenium
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ ./job.sh 20
Attempt Number : 1
Smava Home Page
Traceback (most recent call last):
  File "smava/chrome_perf_smavaHomePage.py", line 4, in <module>
    from timingsclient import Perf
ImportError: No module named timingsclient
check24 Home Page
Traceback (most recent call last):
  File "check24/chrome_perf_check24HomePage.py", line 4, in <module>
    from timingsclient import Perf
ImportError: No module named timingsclient
geld Home Page
Traceback (most recent call last):
  File "geld/chrome_perf_geldHomePage.py", line 4, in <module>
    from timingsclient import Perf
ImportError: No module named timingsclient
finanzcheck Home Page
Traceback (most recent call last):
  File "finanzcheck/chrome_perf_finanzcheckHomePage.py", line 4, in <module>
    from timingsclient import Perf
```

**Comment by vikramvi** [comment]
I've timings library already installed with timings-docker setup ( it works fine when ran outside jenkins setup ) but jenkins is unable to access this setup, please clarify

**Comment by Verkurkie** [comment]
Hi Vikram - this question is related to the client setup. This repo is meant for running the API. Can we move this to https://www.github.com/godaddy/timings-client-py?

**Comment by vikramvi** [comment]
Sure, I've filed new issue https://github.com/godaddy/timings-client-py/issues/2. please review
