### ISSUE TITLE
waterfall graph is broken with current release

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#21]
Please refer to attached screen shot,

![waterfall_graph_broken](https://user-images.githubusercontent.com/308490/33763677-aebd8640-dc11-11e7-86f0-e54dbc634905.png)
Let me know if I need to provide more info to debug this regression ?

**Comment by Verkurkie** [comment]
Note: This is a bug in the API and not a `timings-docker` issue -> should be in https://www.github.com/godaddy/timings/issues

I did reproduce this and identified the code error. It's fixed in the API (version 1.1.1)

If you are running the API with docker-compose (this repo):
> Please delete all old docker "timings" images and run `docker-compose up --build`
> Your API version should be 1.1.1 after this (you can check with http://{api-host}/health)
