### ISSUE TITLE
Step 3. Starting up the API needs documentation step needs update

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#22]
Actual : 

`$ CONFIGFILE=/etc/.perfconfig.js docker-compose up [--build]`

For some it'll be confusing from where `perfconfig.js` has come into the picture

Expected : 

1. For custom config file

`CONFIGFILE={path to config} docker-compose up [--build]`

2. For default config file

`CONFIGFILE=./timings/config/.config_sample.js docker-compose up --build`

**Comment by Verkurkie** [comment]
The reason I added the `CONFIGFILE` environment variable is that the sample config file in `./timings/config/` will be overwritten upon 'git pull' of the `timings-docker` repo. With the new env variable, you can store your config file in a more common location like `/etc/` and not have to worry about it again ...

**Comment by vikramvi** [comment]
I'm referring to [](https://github.com/Verkurkie/timings-docker)

Thanks for pointing out the reason behind storing config file under `/etc/` , can you please add these 2 info points under Step 3

**Comment by Verkurkie** [comment]
You got it! Extra documentation was added to readme.md in commit https://github.com/Verkurkie/timings-docker/commit/70e1f88252f063961699c8f7fbbb727674dd14e3
