### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by testautonation** [Verkurkie/timings-docker#26]
Hi,

I'm trying to view the test results within Kibana and they are not showing up. I also have an error on top saying "No matching indices found: No indices match pattern "cicd-perf*"

I've run out of ideas. Around a month ago I tried the same setup and I managed (on Mac) and now I'm trying again on Ubuntu and I'm getting this.

![kibana](https://user-images.githubusercontent.com/34401714/38466374-79f49054-3b28-11e8-92dc-004a45080783.png)

In the console, when I run the tests I can see the correct response from the api such as:

Navtiming [async]:
{
  "flatSLA": 5000,
  "measured": 925,
  "baseline": 0,
  "threshold": 5000,
  "visualComplete": 3858
}

**Comment by testautonation** [comment]
Back at using a new Mac...did the set up again and it works... no clue what the issue was on Ubuntu.
![image](https://user-images.githubusercontent.com/34401714/38584528-e0c69e18-3d16-11e8-91a6-5ca9d41eb505.png)

**Comment by Verkurkie** [comment]
Hey @testautonation! Glad it's working now! From the first screenshot, it looks like there just isn't any data (based on the message "no matching indices found"). Also the query you're trying (`cicd-perf*`) wouldn't work. Lucene queries have to be based on valid index fields, such as `dl` or `perf.measured`. You can see all the fields in Management->Index Patterns->cicd-perf*. Hope that helps?

**Comment by Verkurkie** [comment]
Also - i noticed the large negative values for the "Actual_plt". Which version of the API are you using? You can check with http://<your_api_server>/health. This was a problem at some point and should be resolved in later versions. Latest version is 1.1.12 ...
