### ISSUE TITLE
Usertiming visualization

### ISSUE THREAD

**Issue by testautonation** [Verkurkie/timings-docker#27]
Am I right in saying that none of the already created visualizations are reading from usertiming data? They all point to navtiming? I'm running test which are using the usertiming calls and nothing shows within the Dashboard.

**Comment by Verkurkie** [comment]
You should see everything. The only exceptions are two visualization that are only relevant to navtiming:

- [TIMINGS] NavTiming metrics
- [TIMINGS] NavTiming-results-with-waterfall-links

Both of these have this filter: `_type:navtiming`.

Other visualizations like `[TIMINGS] List of URLs and PLT` and `[TIMINGS] SLA vs ACTUAL` should show all types

Is there a filter for the dashboard? Sometimes folks will apply a filter to a dashboard and then save/overwrite the dashboard ...

**Comment by Verkurkie** [comment]
![image](https://user-images.githubusercontent.com/947053/38891409-1d36176c-4239-11e8-86e5-43a3f4f86646.png)

I just ran a quick test - here you can see the dashboard showing 3 different types (see the "Perf API" pie chart). There are three different URLs in the "List of URLs and PLT" but there is only one waterfall ...

**Comment by dwanedebonocatena** [comment]
Thanks @Verkurkie for replying. I did not realize that I was actually getting an error in console, and finally figured out that the issue was with a WebdriverIO step that I was calling within the tests that were making use of the usertiming calls. Basically using _browser.waitForExist_ causes this error:

`API error: {
  "status": 422,
  "message": "ValidationError: child 'injectJS' fails because [child 'measureArray' fails because ['measureArray' must contain at least 1 items]]"
}
`

**Comment by testautonation** [comment]
Thanks @Verkurkie for replying. I did not realize that I was actually getting an error in console, and finally figured out that the issue was with a WebdriverIO step that I was calling within the tests that were making use of the usertiming calls. Basically using _browser.waitForExist_ causes this error:

`API error: {
  "status": 422,
  "message": "ValidationError: child 'injectJS' fails because [child 'measureArray' fails because ['measureArray' must contain at least 1 items]]"
}
`

**Comment by Verkurkie** [comment]
Hey @testautonation - i recommend that you include a validation **_after_** injecting the JavaScript into your browser object and **_before_** sending data to the API. For example:

```javascript
...
.execute(decodeURIComponent(injectCode)) // Inject JS code into browser object
.then((response) => {
    // Grab the browser's response - has the perf data!
    if (response.value && response.value.measureArray.length > 0) {    // make sure that we have a measure!
        const browserResponse = response.value;
        return perf.usertiming(browserResponse, perfParams, null) // Send perf data to API
        .then((response) => {
            ...
```
This example makes sure that `measureArray` has at least one member ...

I'm going to guess that you are waiting for a screen element to show up after which you are setting your second `mark`? If the screen element takes too long and the `waitForExists` function reaches its timeout, you won't have the second mark and the injected JavaScript can't produce a `measure` ...

Hope this makes sense?

**Comment by testautonation** [comment]
Yes it perfectly makes sense! Thank you for the explanation @Verkurkie . I'm actually writing a blog post about your library, and have just now published the Part 1 which goes on introducing your library and mentioning the ELK stack. Part 2 will show an example of how to include your JS client to existing WebdriverIO tests. So your reply is right on time :-) Thanks! You can have a look at my post here: [https://testautonation.com/timings-api-part-1/](https://testautonation.com/timings-api-part-1/)

**Comment by Verkurkie** [comment]
Wow - that's a great article! Thanks for posting! Can't wait to see part-2! Let me know if you have any questions or if you need any help!

**Comment by dwanedebonocatena** [comment]
Thank you for your kind words @Verkurkie :-) I'll get right on the next part :-)

**Comment by Verkurkie** [comment]
Hey! Just read [Part-2](https://testautonation.com/timings-api-part-2/) of your article about the **timings API** - very cool! I'm going to point folks at this article as it explains the use of the two functional testing endpoints very well! Thank you so much! 👍

**Comment by dwanedebonocatena** [comment]
Thank you! Glad you liked it! I intend to mention your library again in our next project. Thanks again for your feedback @Verkurkie
