### ISSUE TITLE
Wrong git clone command ?

### ISSUE THREAD

**Issue by pligor** [Verkurkie/timings-docker#28]
As a first step it is mentioned this:
git clone git@github.com/godaddy/timings-docker.git

This used to be part of godaddy and now it is under Verkurkie ?
If yes should this be replaced by: git clone git@github.com:Verkurkie/timings-docker.git  ?

**Comment by Verkurkie** [comment]
No, `timings-docker` was always under Verkurkie. It's an additional repo that i put together to make deployments of the `timings` API itself a little easier. Your command `git clone git@github.com:Verkurkie/timings-docker.git` should work fine. Let me know if you have any issues.
