### ISSUE TITLE
Step 4. Import Kibana assets - From the docker host doesn't work

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#5]
The sub-step **From the docker host** , doesn't work

1.  On Ubuntu python is installed by default, but not sure how to install `requests` 
2.   I tried running command `python import/import.py` from command prompt from directory` timings-docker` got error as below
`python: can't open file 'import/import.py': [Errno 2] No such file or directory`
3.  docker ps output needs to be updated as below
```
   CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                            NAMES
adb19f15c820        timingsdocker_timings         "./wait-for-it.sh ..."   9 minutes ago       Up 9 minutes        0.0.0.0:80->80/tcp                               timings
df10a60e2ef4        timingsdocker_kibana          "/bin/sh -c /usr/l..."   3 hours ago         Up 9 minutes        0.0.0.0:5601->5601/tcp                           kibana
9836a8281d73        timingsdocker_elasticsearch   "/bin/bash bin/es-..."   3 hours ago         Up 9 minutes        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   elasticsearch
```

**Comment by Verkurkie** [comment]
1. There are different ways to do it but the easiest would be `pip install requests` - see also: http://docs.python-requests.org/en/master/user/install/
2. you need to run it from `timings-docker/elasticsearch/` or run `./elasticsearch/import/import.py`
3. Will do - thx!

**Comment by vikramvi** [comment]
Can you please also include info about merits/demerits of running this script inside docker host vs running inside  elasticsearch container ?

**Comment by Verkurkie** [comment]
I added some extra notes to the documentation. The main difference is that the elasticsearch container already has `Python` and the `requests` module pre-installed. See https://github.com/Verkurkie/timings-docker#step-4-import-kibana-assets.

**Comment by vikramvi** [comment]
added to https://github.com/Verkurkie/timings-docker/wiki/FAQ-page

**Comment by tfajks** [comment]
Unfortunatelly https://github.com/Verkurkie/timings-docker#step-4-import-kibana-assets no longer exists. When I open kibana I see "No dashboards matched your search." and "No default index pattern. You must select or create one to continue".

**Comment by Verkurkie** [comment]
Hi @tfajks - you're correct that the link to step-4 is not valid anymore. The import has moved into the API itself. The API will check if import/upgrade is needed and run it accordingly. If for some reason, the import didn't work, you can try to force it by adding the environment variable `UPDATE` to the 'environment' section of the docker-compose file (https://github.com/Verkurkie/timings-docker/blob/master/docker-compose.yml#L42):

```
environment:
  NODE_ENV: "production"
  ES_HOST: "elasticsearch"
  KB_HOST: "${HOSTNAME}"
  UPDATE: "true"
  DEBUG: "true"
```

Please report back if that worked. I am currently working on some syncing code to force the API to wait for elasticsearch `healthy state` before it attempts the import/upgrade ...

**Comment by gsumit1** [comment]
Hello, I have tried after updating it, still the same issue. I am facing.

![image](https://user-images.githubusercontent.com/17493208/154735638-0e095971-ee5c-4362-ac99-9e5da671e70d.png)
