### ISSUE TITLE
fix-permission-denied

### ISSUE THREAD

**Issue by kaygee** [Verkurkie/timings-docker#7]
Hi @Verkurkie I was getting the following error when attempting to start up using Docker for OSX.

`ERROR: for timings  Cannot start service timings: oci runtime error: container_linux.go:265: starting container process caused "exec: \"./wait-for-it.sh\": permission denied"`

I resolved it by...

`chmod +x wait-for-it.sh`

I tried to PR, but... of course I don't have permission. :)

**Comment by Verkurkie** [comment]
Thx for pointing this out! Update pushed: https://github.com/Verkurkie/timings-docker/commit/856f72514fc695dd09e3788e68f4a0f8f47b3fb0
