### ISSUE TITLE
Is is possible to capture just one of the element load time in waterfall ?

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#8]
I have shown the demo project to developer and he really liked it. But his requirement is if I can capture particular element's load time it will be more helpful.

e.g. waterfall shows almost 30+ elements getting loaded
- the first element is of type document belonging to main webpage being loaded and he just needs this time to capture
- the webpage takes data from google analytics as well, which may delay sometime.  Thus we want to capture single element in that page.

**Comment by Verkurkie** [comment]
Elements are captured as 'resources' which are used to build the waterfalls. From the main Kibana dashboard, you can click on the 'waterfall' links to load the waterfall page. On the waterfall page, you can click on the colored bar of the resource you're interested in - that will take you back to Kibana and load the `TIMINGS-Resources` dashboard. This dashboard provides charts and data for individual resources. If you want, you can create filtered versions of this dashboard for particular resources so it's easier to load them in the future. Does that help?

**Comment by vikramvi** [comment]
Thanks, let me try and update back

**Comment by vikramvi** [comment]
This is not working as expected
- Clicking on colored bar of the resource; take to blank page 
http://elasticsearch:5601/app/kibana#/dashboard/CICD-Resources?_g=(time:(from:now-7d,mode:quick,to:now))&_a=(query:(query_string:(analyze_wildcard:!t,query:'dl:"www.smava.de%2Fkreditanfrage%2Fkreditantrag.html%3Froute%3DV1"')))

clicked on first row 

![screenshot from 2017-11-02 20-53-36](https://user-images.githubusercontent.com/308490/32347120-f34c3cd4-c00f-11e7-999b-5a388abb7d49.png)

**Comment by Verkurkie** [comment]
Ah! That is supposed to go to `...dashboard/TIMINGS-Resources?_g...`
I can make the necessary changes!
Can you validate that it works if you change `CICD-` to `TIMINGS-` in the url?
Also, does http://elasticsearch:5601 actually reflect your kibana machine?

**Comment by vikramvi** [comment]
Please find below update

> Can you validate that it works if you change CICD- to TIMINGS- in the url?

even after changing url, blank page is loading

> Also, does http://elasticsearch:5601 actually reflect your kibana machine?

Please refer to attached screen shots each for localhost kibana and elastic search
![elastic_search](https://user-images.githubusercontent.com/308490/32367765-91888a88-c083-11e7-98f2-378854eca5a5.png)
![kibana](https://user-images.githubusercontent.com/308490/32367766-91ab458c-c083-11e7-991d-55d56c27ed7e.png)

- I think generated url is wrong.

**Comment by vikramvi** [comment]
I got it working with below url

`http://localhost:5601/app/kibana#/dashboard/TIMINGS-Resources?_g=(time:(from:now-7d,mode:quick,to:now))&_a=(description:'',filters:!(),options:(darkTheme:!f),panels:!((col:1,id:%5BTIMINGS%5D-Resource-duration-breakdown,panelIndex:1,row:1,size_x:6,size_y:4,type:visualization),(col:7,id:%5BTIMINGS%5D-Resource-timings,panelIndex:2,row:1,size_x:6,size_y:4,type:visualization),(col:1,id:%5BTIMINGS%5D-List-of-Resources,panelIndex:3,row:5,size_x:8,size_y:7,type:visualization),(col:9,id:'6cdb3d80-845a-11e7-a313-8d4ec725b2f9',panelIndex:4,row:5,size_x:4,size_y:7,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'dl:%22www.smava.de%2Fkreditanfrage%2Fkreditantrag.html%3Froute%3DV1%22')),timeRestore:!t,title:TIMINGS-Resources,uiState:(P-3:(vis:(params:(sort:(columnIndex:0,direction:desc)))),P-4:(vis:(params:(sort:(columnIndex:!n,direction:!n))))),viewMode:view)`

but the graph looks weird, I can't get to see page loading timing.
Is this customizable to add specific parameters to capture ?

**Comment by Verkurkie** [comment]
Addressing the URL issue:
* You were right! The URL was the problem! I have added the ability to set the kibana hostname in the config of the API (`../timings-docker/timings/config/.config.js`)
* For reference, see the new 'env' key in the example config here:
 https://github.com/godaddy/timings/blob/master/CONFIG.MD. 
* After setting the kibana host in the API config file, run `docker-compose up --build` to make sure you grab the latest docker container
* **NOTE:** ideally, the kibana host name should be the full hostname (fqdn) of your **docker host** so others can reach it too!
* You can validate that the hostname was picked up by the API server by hitting `http://{docker_host}/health`

Addressing the graph configuration:
* The metrics shown in the graph are defined in the "visualization" which you can edit via the "visualize" tab. 
* The graph visualizations in this dashboard are `[TIMINGS-RES] Resource duration breakdown` and `[TIMINGS-RES] Resource timings` and you can absolutely edit those! Just need some basic Kibana skills. This is a good starting point: https://www.elastic.co/guide/en/kibana/current/createvis.html

**Comment by vikramvi** [comment]
- I have used **timings-docker** project to do the setup for timings api, elastic search and kibana. In this case how to set value of kibana hostname ?
- I ran command **docker-compose up --build**, but still url has got CICD string instead of TIMINGS, am I doing something wrong here ?
-  Can you please add more info under **Configure the API for Kibana** section in README

**Comment by Verkurkie** [comment]
* There are two things to look at: i) the API config and ii) the kibana import.py script:
  1. For **timings-docker**, the config is: `timings-docker/timings/config/.config.js`
  2. Running the import.py script with additional arguments. The `-a` argument with the hostname of the API server and the `-k` argument with the hostname of the Kibana server (they can be the same!)
* The `docker-compose up --build` command should work. You can see the new code here: https://github.com/godaddy/timings/blob/d0fe6125eb72ca961c5ac7f349228ae004ba4f14/public/js/waterfall.js#L292. Can you run `docker images` and look at the age of your `timingsdocker_timings` image? You can also remove this image with `docker rmi <image_id>` and then run `docker-compose up --build`. This should build a new image ...
* I was hoping that https://github.com/godaddy/timings#installing-elasticsearch-and-kibana would be sufficient but always open to suggestions :)
* Yes it is. Only difference is the location of the config file ... in case of timings-docker, it is in the `timings-docker/timings/config/` directory

Hope this helps?

**Comment by vikramvi** [comment]
Thanks a ton for detailed info.  Your solution has worked perfectly, thus marking issue as verified & fixed.
