### ISSUE TITLE
step "Now go and check out Kibana to make sure everything looks A-OK!" needs more info

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#9]
Please refer to attached screen shot of Kibana before running import.py

![kibana](https://user-images.githubusercontent.com/308490/32346818-f143b3dc-c00e-11e7-9d07-4cb48dc2a46d.png)

Even after running import.py inside container and refreshing + waiting for few minutes; doesn't change anything.

I've checked output of this script and everything is shown as PASS.

Please clarify if something missing out here

May be adding screen shots of before and after import can be useful

**Comment by Verkurkie** [comment]
The dashboard in this screenshot is actually expected. The import worked! The presence of "cicd-perf" in the index drop-down and `count_fail` and `count_pass` under "available fields" are all indicators of a successful import.

Excellent idea to add some screenshots to the documentation! Go check it out here: https://github.com/Verkurkie/timings-docker#step-5-setup-kibana

**Comment by vikramvi** [comment]
Thanks for detailed info. Closing issue as verified fixed
